### ISSUE TITLE
What next?

### ISSUE THREAD

**Issue by chilicat** [opensourcehacker/sevabot#11]
Hello,
just found this interesting project and thought why not :) 
I just did the vagrant installation. What next? What do I have to do to get it running?
I cannot connect to the VM via VNC so I cannot setup skype. Or did I miss something?

**Comment by miohtama** [comment]
Hi Chilicat,

I am preparing a huge documentation update today, so you should soon see some more instructions!

Meanwhile you can reach me on IRC channel #opensourcehacker on irc.freenode.net

(Brazilian working hours)

**Comment by miohtama** [comment]
Ok, please check README now and tell if the documentation leaves you cold handed in somepoint?

**Comment by tenpn** [comment]
I've been playing this morning, and have got the bot running on OSX following the docs. I can !ping it and everything. However when it comes to trying to post a message from a shell script, I can't make it work. There's no docs, but following the examples in the docs, I've tried doing a curl to http://localhost:5000/msg/ but get a 404. 

I can point my browser to localhost:5000 and look around fine.

Would you get that error if the md5 wasn't set up correctly? More documentation on this would be great.

**Comment by tenpn** [comment]
After digging around in the source, turns out the post message api is as follows:

```
curl --data-urlencode chat_id="..." --data-urlencode message="..." --data-urlencode shared_secret="..." http://localhost:5000/message/
```

**Comment by miohtama** [comment]
Is there any particular line/example wrong/misleading in the docs? Let me know and I can fix it.

This is totally possible as the docs have undergone major shuffle lately.

**Comment by miohtama** [comment]
Also you can edit docs directly here in your browser and suggest a patch youself

https://github.com/opensourcehacker/sevabot/tree/master/docs/source

(Just hit Fork and edit button)

**Comment by tenpn** [comment]
Made a small pull request noting the holes in the documentation and showing a brief workaround.

**Comment by tenpn** [comment]
pull request #21 btw
