### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by grundic** [opensourcehacker/sevabot#15]
I've got some ideas I would like to implement, take a look and maybe add some yours:
1. Implement login for administrators - http://flask.pocoo.org/docs/tutorial/views/#login-and-logout
2. Make it possible for bot to automatically accept incoming contact request or make it possible to do via web interface
3. Add/search contacts from web interface 
4. Implement chat grouping: for example, I've got several people, who are interested in notification on build failure. I can configure several url handlers on Teamcity. But it's better if we can implement chat grouping and sending notification for group chat will send a message to all configured people.
5. Change status from web
6. Favicon

**Comment by miohtama** [comment]
I have been thinking some ideas myself and some of seems to be similar to yours :)

Would it be possible for you to open a separate issue for each idea on Github and add "Enhanchement" label on them? I'll also put out some of my ideas for discussion.

I am also on #opensourcehacker channel in irc.freenode.net for chat during Brazilian working hours.
