### ISSUE TITLE
Logo needed

### ISSUE THREAD

**Issue by miohtama** [opensourcehacker/sevabot#22]
I think we do not have permission to use Skype logo unless we are prepared to have Microsoft lawyers ripping of our skin (current favicon)

We need a logo what we can use as
- Skype avatatar for Sevabot
- Favicon on admin
- Favicon on docs
- Icon on github 

etc.

Any ideas?

**Comment by grundic** [comment]
I've asked one of my collegues if he can help.. He said 'yes' :)
We need to invent theme of logo and icon.

May be some funny robot?

By the way, I'm on #opensourcehacker on FreeNode.

**Comment by miohtama** [comment]
I'd like to have something inside a heart (like love). Sevabot loves you.

Like in Portal (the computer game) they have Companion Cube.

On Sat, Dec 22, 2012 at 6:58 AM, Grigory Chernyshev <
notifications@github.com> wrote:

> I've asked one of my collegues if he can help.. He said 'yes' :)
> We need to invent theme of logo and icon.
> 
> May be some funny robot?
> 
> By the way, I'm on #opensourcehacker on FreeNode.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opensourcehacker/sevabot/issues/22#issuecomment-11635297.

## 

Mikko Ohtamaa
http://opensourcehacker.com
http://twitter.com/moo9000

**Comment by grundic** [comment]
Some samples:
http://www.deviantart.com/download/78490727/Companion_Cube_Vector_by_CoffeeDaze.png
http://fc05.deviantart.net/fs51/i/2009/268/0/5/Companion_cube_2D_from_3D_by_Jasontti.png

**Comment by miohtama** [comment]
Nice. But I think it's little bit too complex for a logo. Let me whip up
something.

On Sat, Dec 22, 2012 at 10:46 AM, Grigory Chernyshev <
notifications@github.com> wrote:

> Some samples:
> 
> http://www.deviantart.com/download/78490727/Companion_Cube_Vector_by_CoffeeDaze.png
> 
> http://fc05.deviantart.net/fs51/i/2009/268/0/5/Companion_cube_2D_from_3D_by_Jasontti.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opensourcehacker/sevabot/issues/22#issuecomment-11636838.

## 

Mikko Ohtamaa
http://opensourcehacker.com
http://twitter.com/moo9000

**Comment by miohtama** [comment]
I pushed a simplified down version in docs/source/images

The orignal is created with Inkscape.

It should also contain 24 px favicon png. 16 px is too low resolution, so I suggest using 32 or 24 px favicon.
