### ISSUE TITLE
module Q&A

### ISSUE THREAD

**Issue by wmzaru** [opensourcehacker/sevabot#25]
Tell me how to create a module like "question and answer"
for example:
!qa name 
will test1
!qa name2 
will test2 
etc.

**Comment by miohtama** [comment]
1. First read a Python programmign tutorial http://docs.python.org/2/tutorial/ to learn basics how to program in Python (or any other your favorite programming langauge)
2. Create a command line application which parses command line output and extracts the argument out of it. Example is here https://github.com/opensourcehacker/sevabot/blob/master/modules/weather.py
3. Drop this command line application to the modules folder as instructed https://sevabot-skype-bot.readthedocs.org/en/latest/commands.html#creating-custom-commands
