### ISSUE TITLE
How to connect to VNC session in Windows

### ISSUE THREAD

**Issue by wmzaru** [opensourcehacker/sevabot#29]
Shuts down bot. Have to run it again. In what could be the problem?

**Comment by miohtama** [comment]
This issue report does not have enough details to be answerable. In fact, I have no idea what you are trying to say. Pleas add more details. I suggest you study best pratices how to ask questions on Internet forums.

http://opensourcehacker.com/2011/03/17/rfc-simple-internet-question-asking-protocol-for-human-beings/

http://www.catb.org/esr/faqs/smart-questions.html

**Comment by wmzaru** [comment]
reinstalled ubuntu 12.04 server
According to the instructions https://sevabot-skype-bot.readthedocs.org/en/latest/ubuntu.html
Trying to install a bot on your instructions, nothing.
First you have not installed Skype, now can `t go through x11vnc, (XOpenDisplay (" ") failed.)

**Comment by miohtama** [comment]
We need actual error messages and commands which fail.

**Comment by miohtama** [comment]
Copy paste your terminal

**Comment by miohtama** [comment]
Can you paste step by step what's happening when you are following steps on here:

https://sevabot-skype-bot.readthedocs.org/en/latest/ubuntu.html#setting-up-skype-and-remote-vnc

Do you follow instructions by the letter?

Did you properly start VNC server on the server?

Did you properly create SSH tunnel tunnel to the server before using VNC viewer?

**Comment by wmzaru** [comment]
skype@wmza1:~$ sudo ssh -L 5900:localhost:5900 skype@188.120.225.67
[sudo] password for skype:
skype@188.120.225.67's password:
Welcome to Ubuntu 12.04.1 LTS (GNU/Linux 2.6.18-308.el5.028stab099.3PAE i686)
 Documentation:  https://help.ubuntu.com/
Last login: Wed Jan 23 20:00:46 2013 from 91.204.60.5
skype@wmza1:~$
skype@wmza1:~$ git clone git://github.com/opensourcehacker/sevabot.git
Cloning into 'sevabot'...
remote: Counting objects: 955, done.
remote: Compressing objects: 100% (458/458), done.
remote: Total 955 (delta 544), reused 885 (delta 474)
Receiving objects: 100% (955/955), 882.16 KiB | 56 KiB/s, done.
Resolving deltas: 100% (544/544), done.
skype@wmza1:~$

**Comment by wmzaru** [comment]
skype@wmza1:~$sevabot/scripts/start-server.sh start
Setting default value
Failed to read: session.forcePseudoTransparency
Setting default value
Failed to read: session.colorsPerChannel
Setting default value
Failed to read: session.doubleClickInterval
bla-bla-bla
Setting default value
Failed to read: session.tabPadding
Setting default value
Failed to read: session.styleOverlay
Setting default value
Failed to read: session.slitlistFile
Setting default value
Failed to read: session.appsFile
Setting default value
Failed to read: session.tabsAttachArea
Setting default value
Failed to read: session.cacheLife
Setting default value
Failed to read: session.cacheMax
Setting default value
Failed to read: session.autoRaiseDelay
Setting default value
Failed to read: session.screen0.opaqueMove
Setting default value
Failed to read: session.screen0.fullMaximization
Setting default value
Failed to read: session.screen0.windowPlacement
Setting default value
Xlib:  extension "RANDR" missing on display ":1".
Failed to read: session.ignoreBorder
Setting default value
Failed to read: session.screen0.iconbar.usePixmap
Setting default value
sevabot/scripts/start-server.sh: line 54: sevabot/scripts/../venv/bin/sevabot: N                                                                                        o such file or directory
Started Sevabot web server process id 26125
skype@wmza1:~$

**Comment by wmzaru** [comment]
skype@wmza1:~$ sevabot/scripts/start-vnc.sh start
Xvfb is running
fluxbox is running
skype is running
Sevabot NOT running
OVERALL STATUS: NOT RUNNING PROPERLY
The server doesn't run.
Use "sevabot/scripts/start-server.sh" to start the server
skype@wmza1:~$

**Comment by wmzaru** [comment]
skype@wmza1:~$ sevabot/scripts/start-server.sh start
Xvfb already running
fluxbox already running
skype already running
sevabot/scripts/start-server.sh: line 54: sevabot/scripts/../venv/bin/sevabot: No such file or directory
Started Sevabot web server process id
skype@wmza1:~$

**Comment by wmzaru** [comment]
skype@wmza1:~$ vncviewer localhost
Error: Can't open display:
skype@wmza1:~$

**Comment by miohtama** [comment]
Got it! 

you need to run command

vncviewer 

On your local linux computer, not on the server.

vncviewer command connects to your local computer port 5900 which SSH transfers to server where VNC server waits for the connection.

**Comment by wmzaru** [comment]
I have windows

**Comment by miohtama** [comment]
Use any Windows VNC software. Also the command "ssh" is to connect the server. I have no idea how Windows VNC softwares work, does your server need a tunnel, etc. so you need to figure out that yourself.

**Comment by miohtama** [comment]
I am sorry, I cannot provide Windows support as I have not used Windows for 10 years.

**Comment by miohtama** [comment]
My friend told me to use something called TinyVNC

**Comment by Aegil** [comment]
RealVNC or TinyVNC should work. How are you ssh'ing to the server? I guess you can do the port forwards using putty or something similar.

Also if you run just the below vnc will listen on all ips and you can vnc directly to the servers ip. The vnc over ssh is for security as vnc is a weak service and we are using it without a password from what I can see in start-vnc.sh
If the server is on your local network the below should be fine for initial startup so that you can sign into skype and allow sevabot access to the Skype. Then once thats all confirmed working you could restart the process and restart vnc so that its bound to localhost and use vnc over ssh going forward. 

x11vnc -display :1 -bg  -nopw -xkb

**Comment by miohtama** [comment]
Also port forwarding is not strictly necessary if your server is not firewalled and you can access any other ports (besides SSH)

**Comment by wmzaru** [comment]
Aegil (x11vnc-дисплей: 1-BG-nopw-XKB)
Thanks. Help with connecting to vnc.

**Comment by aaomidi** [comment]
/venv/bin/sevabot: No such file or directory
 I'm having the same problem, can't setup venv for some reason

**Comment by aaomidi** [comment]
I have VNC setup. this is the problem:
Cannot find sdist setuptools-_.tar.gz
Cannot find sdist pip-_.tar.gz
When doing python virtualenv.py venv

**Comment by Aegil** [comment]
Try running the below to get setuptools . 
wget https://pypi.python.org/packages/source/s/setuptools/setuptools-1.1.7.tar.gz
Also I tried installing pip from the repos and I had pip in /usr/share/python-virtualenv/pip-1.1.tar.gz so I copied this to the same folder as sevabot and then it worked.
