### ISSUE TITLE
not running a webhook chatting

### ISSUE THREAD

**Issue by wmzaru** [opensourcehacker/sevabot#33]
when connected to vebhook zapier.сom chat prints a blank line, a pop window Skype says that "the message is deleted."
zapier.com 
URL webhook POST:
http://188.x.x.x:5000/message/861933af9506dafc90d6e55c0e991e91/password/
if you enter:
(http://188.x.x.x:5000/zapier/861933af9506dafc90d6e55c0e991e91/password/
ERROR 404)

**Comment by miohtama** [comment]
I updated instructions 

https://sevabot-skype-bot.readthedocs.org/en/latest/zapier.html

Please take git pull (version 1.2dev0) and it should be fixed here!
