### ISSUE TITLE
Sevabot on the Raspberry Pi

### ISSUE THREAD

**Issue by pig-cop** [opensourcehacker/sevabot#35]
Is this possible? I'm sorry I'm quite the noob, but it would be nice a guide in the documentation on how to perform a headless installation on the Raspberry Pi!

**Comment by felixfyi** [comment]
Yes it should be possible. In order to setup Sevabot properly you need to preinstall an OS (preferred for Sevabot: Ubuntu) and follow the installation guide.

**Comment by miohtama** [comment]
I think generic Linux guidelines apply to Rasperry Pi. We have instructions for Ubuntu based Linuxes as they are the most common. Unfortunately we cannot guide with other distributions as we (as in people I know to hang on #opensourcehacker IRC channel) don't use them. It's possible but if you do it you are on your own. We'd really like to receive feedback (documentation) how it happens :)
