### ISSUE TITLE
remote hosts cannot relay messages to http api

### ISSUE THREAD

**Issue by tc0nn** [opensourcehacker/sevabot#50]
When I use the provided send.sh file, I get validation failed. I assume its because I'm not sending from the same host that is listening on port 5000 although I can use the web interface from my remote host just fine. Any suggestions? did I miss a setting?

**Comment by tc0nn** [comment]
./send.sh test1
Validation failed!

**Comment by tc0nn** [comment]
Never mind. Special characters in the secret were fouling this up.

**Comment by miohtama** [comment]
Hi. Thanks for notifying this. Any idea how to escape special characters in send.sh correctly?
