### ISSUE TITLE
Latest Jenkins Notification Plugin causes Exception (includes fix)

### ISSUE THREAD

**Issue by garyhodgson** [opensourcehacker/sevabot#51]
Hi,

Whilst trying to get sevabot working with Jenkins I noticed that the latest version of the Notification Plugin caused an exception.  

The fix appears to be changing the following line (https://github.com/opensourcehacker/sevabot/blob/master/sevabot/frontend/api.py#L192) to:

```
payload = request.json
```

(seemed excessive to create a pull request)

Cheers,
Gary

**Comment by justnom** [comment]
Hello,

Fixed this in my fork and its been merged into the upstream master.

**Comment by miohtama** [comment]
Closed, as fixed by @justnom .
