### ISSUE TITLE
Missing steps on the tutorial

### ISSUE THREAD

**Issue by comentarinformal** [opensourcehacker/sevabot#53]
I've tried to install sevabot on a new headless Ubuntu server. Everything goes fine until 
. venv/bin/activate
, which warns you of two missing things: pip-_.tar.gz and setuptools-_.tar.gz . While anyone linux-savvy knows to just get them from somewhere and install them, not everybody is, so they might ignore it and keep going.
That ends with the user stuck trying to start up Sevabot, failing as those two packets don't exist.

Installation step-by-step should be updated for that.

**Comment by nightrise** [comment]
Agreed, this is an issue I also encountered. It seems to be enough to simply download and copy the pip and setuptools tar.gz into the sevabot directory. Being relatively new to python, at first I thought this was an issue with my install since pip and setuptools were both available for use (and could be imported with no problem in the interpreter).

**Comment by miohtama** [comment]
I'll look to make the process little bit simpler in the next release. I
have some ideas, but not have had time to give love to Sevabot lately.

On 24 August 2013 10:25, nightrise notifications@github.com wrote:

> Agreed, this is an issue I also encountered. It seems to be enough to
> simply download and copy the pip and setuptools tar.gz into the sevabot
> directory. Being relatively new to python, at first I thought this was an
> issue with my install since pip and setuptools were both available for use
> (and could be imported with no problem in the interpreter).
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/opensourcehacker/sevabot/issues/53#issuecomment-23204541
> .

## 

Mikko Ohtamaa
http://opensourcehacker.com
http://twitter.com/moo9000

**Comment by bkmeneguello** [comment]
Please, just add to https://sevabot-skype-bot.readthedocs.org/en/latest/ubuntu.html that the files in  https://github.com/pypa/virtualenv/tree/develop/virtualenv_support must be downloaded to ~/sevabot dir. It took me an hour to figure out.

**Comment by miohtama** [comment]
I am not sure if this is a correct solution, as your distribution should be providing these files in the first place and there should be not need to manually download them.

I would first like to figure out how to repeat this issue with Ubuntu server, as I have not conforted the issue and I am running Sevabot on Ubuntu myself.

**Comment by Aegil** [comment]
I had a similar issue installing it on ubuntu, downloaded them manually but later found they were available from the repo but needed to be in the specific folder for some reason

**Comment by miohtama** [comment]
I have now updated the instructions to use the system virtualenv for Python 12.04.

https://github.com/opensourcehacker/sevabot/commit/842390e28e1b829f78b8458887deea2cecb8e512

However this will break when Ubuntu 14.04 will be released with Python 3 and Skype4Py is Python 2.7 only.
