### ISSUE TITLE
Docker Containers - Couldn't connect to XServer

### ISSUE THREAD

**Issue by joshstrange** [opensourcehacker/sevabot#56]
I have been playing around with [Docker](http://www.docker.io/) and containers recently and when I stumpled accross Sevabot I decided to try and package it up as container. I was able to follow all the steps for Ubuntu (I had to take some extra steps b/c containers are so bare-bones) but when I got to the:

```
SERVICES="xvfb fluxbox skype" ~/sevabot/scripts/start-server.sh start
```

step I get the following:

```
skype@9641df0a5587:~$ SERVICES="xvfb fluxbox skype" ~/sevabot/scripts/start-server.sh start
starting Xvfb
starting fluxbox
Error: Couldn't connect to XServer
Fatal server error: Could not create lock file in /tmp/.tX1-lock
```

I have done quite a bit of googling on this but as I don't have much experience with fluxbox I was not able to get very far. Some people suggested the culprit might be [.xinitrc](http://www.linuxquestions.org/questions/slackware-14/fluxbox-error-couldn't-connect-to-xserver-365864/) but I tried a couple suggestions none worked.

I have run programs over X11 before (Am I phrasing that right) without busybox and since that is the end goal (To login and change skype settings). I am going to attempt to get that working a different way but I thought I would ask here if you have seen that error before.

All of my progress thus far can be found on index.docker.com [joshstrange/sevabot](https://index.docker.io/u/joshstrange/sevabot/).

**Comment by miohtama** [comment]
Nice progress! I was thinking one day to try to get multiple Sevabots running in Dockers (so you could have it as a hosted service), but that would require also some automatication to enter Skype passwords etc. Skype does not natively support such interaction.

Also Skype API is going be axed, so maybe it is time to build alternative backend for Sevabot.

**Comment by joshstrange** [comment]
@miohtama Yeah, I really wanted to write a little bot that could sit in our skype chats to either post things (Like code deployments, CI reports, etc) and/or be listening for us to do things like your example (something along the lines of "!bot deploy dev PRODUCT" to deploy a codebase out to our servers). It's too bad they are killing off the API (I found that out after a few more hours of playing around/googling), now I guess my mission is to convince the team I work on to switch to something I can hook into. Thanks!
