### ISSUE TITLE
how to send message via http request ?

### ISSUE THREAD

**Issue by dedihost** [opensourcehacker/sevabot#60]
I need something like this:

localhost:5000/message/secretid/chatid/here is text sended to user
Please, help me.

**Comment by miohtama** [comment]
The example code is available here: 

https://sevabot-skype-bot.readthedocs.org/en/latest/webhooks.html

**Comment by dedihost** [comment]
I didnt understand, can you give me a example ?

**Comment by miohtama** [comment]
The linked documentation contains examples for different programming languages (shell scripting, Python). I suggest you study them how to send a message.

If you don't find this examples helpful enough we need a find person who can help you with your own programming language.

The sending message action is not very complex and anybody with intermediate programming experience should be able to help you.

**Comment by dedihost** [comment]
localhost:5000/message_unsigned/chat_id=301fe7e91cf0d5977f59f366e28a9f20&message=test
This is not correct or correct ?
I look at message_unsigned and i read about http post requests and i think the url is correct written.
I need this to use in AMXX plugin for Counter-Strike servers (call admin via skype).
Thanks for any help.

**Comment by comentarinformal** [comment]
(lol, Thunderbird's now sending it to spam...)
If you read about http POST requests, you would know why that URL isn't going to work.

**Comment by miohtama** [comment]
The parameters are correct.
That is not a HTTP POST request, that is most likely a HTTP GET request. HTTP POST request is constructed in whatever programming language you are using and you do not give parameters in URL.

I suggest you consult AMXX / Counter-Strike development community how to do HTTP POST requests in its plugin programming environment.

**Comment by dedihost** [comment]
OK! Thanks for fast reply's :)
