### ISSUE TITLE
Sevabot's frontend on nginx?

### ISSUE THREAD

**Issue by comentarinformal** [opensourcehacker/sevabot#74]
Hello there.
I'm not very sure how I would go about setting Sevabot's webpages on nginx, rather than Apache.
By a simple grep I've seen that it revolves around venv, which is different from editing some configuration files...
A little hand?

**Comment by miohtama** [comment]
There shouldn't be anything special how Sevabot servres the page.

Normal Nginx `proxy_pass` directive should cut it.
