### ISSUE TITLE
OpenVZ can't start sevabot anymore.

### ISSUE THREAD

**Issue by comentarinformal** [opensourcehacker/sevabot#76]
My hosting has updated all our servers with the new security fix (found [here](http://kb.parallels.com/en/122142)); since it did, I can't start sevabot anymore.
It seems to have stopped detecting the display it starts up, trying to start more than one until the error
_XSERVTransSocketINETCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
Fatal server error:
Cannot establish any listening sockets - Make sure an X server isn't already running

...appears.
That fix seems to have something to do with user privileges and their containment -- maybe Sevabot needs to use something as a determinated user? For example, adding the skype user as root (!!) to run the start-server.sh? But then again, that doesn't make a lot of sense if the problem is with displays...

Entire logs when running the start-server.sh start command [here](https://gist.github.com/comentarinformal/78c460917f589023bfdf).
Running 
Linux (hostname)2.6.32-042stab090.5 #1 SMP Sat Jun 21 00:15:09 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux
(Ubuntu)
Feel free to ask for any information that might be useful.

**Comment by foleranser** [comment]
Maybe she's decided to leave this planet because her people needs her.
