### ISSUE TITLE
Issue with group chats

### ISSUE THREAD

**Issue by Althenar** [opensourcehacker/sevabot#78]
I'm having trouble with Sevabot in group chats. Everything works fine in conversations with single people, however when I join a chat, every message sent to that chat results in the following exception:

Exception in thread Skype4Py MessageStatus event scheduler:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/Skype4Py/utils.py", line 225, in run
    handler(_self.args, *_self.kwargs)
  File "/home/skype/sevabot/sevabot/bot/bot.py", line 95, in handleMessages
    logger.debug("Incoming %s - %s - %s: %s" % (status, msg.Chat.FriendlyName,
  File "build/bdist.linux-x86_64/egg/Skype4Py/chat.py", line 245, in _GetFriendlyName
    return self._Property('FRIENDLYNAME')
  File "build/bdist.linux-x86_64/egg/Skype4Py/chat.py", line 33, in _Property
    return self._Owner._Property('CHAT', self.Name, PropName, Value, Cache)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 296, in _Property
    value = self._DoCommand('GET %s' % jarg, jarg)
  File "build/bdist.linux-x86_64/egg/Skype4Py/skype.py", line 281, in _DoCommand
    raise SkypeError(int(errnum), errstr)
SkypeError: [Errno 105] Invalid chat name

Also the group chat ID does not show up in /chats/. Any ideas what might be the problem?

I'm running sevabot on CentOS 6 with python 2.6 and skype 4.3.0.37

**Comment by miohtama** [comment]
The upstream bug is here and it is not triaged yet:

https://github.com/awahlig/skype4py/issues/34

**Comment by Althenar** [comment]
Thanks! I'll try downgrading my skype install until this is fixed upstream

**Comment by miohtama** [comment]
Please tell me if you can find a working Skype version.

AFAIK Microsoft doesn't publish old .debs and binary redistribution is forbidden :(

**Comment by Althenar** [comment]
The files are still available, only the links to them are removed. I've managed to dig up two older versions:
http://download.skype.com/linux/skype-4.1.0.20.tar.bz2
http://download.skype.com/linux/skype-4.2.0.11.tar.bz2

Unfortunately 4.1 segfaults on my server, however the 4.2 runs fine, and the error is gone. I still have some problems with group chats (seems like the client doesn't receive chat invites from newer versions), but it's a step forward.

**Comment by miohtama** [comment]
This is very good to know! Can you please add the same information to the upstream bug?

**Comment by someoneEQ** [comment]
For what its worth, I am also running into this.  Microsoft forced us to upgrade our linux client (it stopped working, and could not sign in without upgrading), and ever since we did, sevabot cannot see _new_ chats, old / existing chats seem fine though.  We upgraded to 4.3.0.37, I'll try the 4.2.0.11 above.

**Comment by gii-brian-johnson** [comment]
Note that this seems to work if the sevabot user creates the channel (vs is added to an existing)
