### ISSUE TITLE
Could not load settings file: settings.py

### ISSUE THREAD

**Issue by comentarinformal** [opensourcehacker/sevabot#79]
So I remember having this problem previously, but I can't remember how I fixed it.
I have the settings.py file at /home/skype/sevabot, and doing 
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo $DIR
outputs exactly that, /home/skype/sevabot
However, when I try to start sevabot ( SERVICES="sevabot" ./scripts/start-server.sh start ), it doesn't do anything for some seconds, then

Could not load settings file: settings.py
Started Sevabot web server process id

I've even symlinked it on ./sevabot, ./sevabot/frontend, to no avail.

Using the latest version, fetched a day or two ago.
Any ideas of what could be causing this?

**Comment by comentarinformal** [comment]
Is anyone there?

**Comment by foleranser** [comment]
Nevermind this devs, she's alive now.
