### ISSUE TITLE
Installation fails on Windows: Pip and setuptools fail to install

### ISSUE THREAD

**Issue by Lolmewn** [opensourcehacker/sevabot#94]
I tried installing Sevabot via the tutorial, which gave me the following output: 

```
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> cd .\Documents\SkypeBot
PS C:\Users\Administrator\Documents\SkypeBot> git clone git://github.com/opensourcehacker/sevabot.git
Cloning into 'sevabot'...
remote: Counting objects: 1649, done.
remote: Total 1649 (delta 0), reused 0 (delta 0), pack-reused 1649
Receiving objects: 100% (1649/1649), 1.49 MiB | 1.16 MiB/s, done.
Resolving deltas: 100% (771/771), done.
Checking connectivity... done.
PS C:\Users\Administrator\Documents\SkypeBot> cd sevabot
PS C:\Users\Administrator\Documents\SkypeBot\sevabot> powershell -NoProfile -ExecutionPolicy unrestricted -Command "add-
content -path virtualenv.py -value(new-object net.webclient).DownloadString('https://raw.github.com/pypa/virtualenv/mast
er/virtualenv.py')"
PS C:\Users\Administrator\Documents\SkypeBot\sevabot> python virtualenv.py venv
New python executable in venv\Scripts\python.exe
Cannot find a wheel for setuptools
Cannot find a wheel for pip
Installing setuptools, pip...
  Complete output from command C:\Users\Administrat...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:
]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pip
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "virtualenv.py", line 2352, in <module>
    main()
  File "virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command C:\Users\Administrat...v\Scripts\python.exe -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptool
s pip failed with error code 1
```

I've tried to install Setuptools and pip seperately which seemed to go just fine - however, it seems sevabot doesn't use those. 
Using Windows 2012 Server R2 64 bit, Python 2.7 32 bit (x86), and also did it in Powershell x86 just to be sure. Suggestions?

**Comment by miohtama** [comment]
Try Windows virtualenv installation instructions from official source.
Maybe something has changed.

**Comment by Lolmewn** [comment]
Tried the official installation instructions - exact same output. Guess the issue is not sevabot but venv. I contacted the dev of venv but he can't test much as he has no windows available (apparently). Idea's?

**Comment by hajekj** [comment]
I had the same issue, in the same environment, but the solution to work for me works like this:
1. Perform the "Solution" step from here: https://github.com/pypa/pip/issues/1064
2. As per http://sevabot-skype-bot.readthedocs.org/en/latest/windows.html
- git clone git://github.com/opensourcehacker/sevabot.git
- cd sevabot
- powershell -NoProfile -ExecutionPolicy unrestricted -Command "add-content -path virtualenv.py -value(new-object net.webclient).DownloadString('https://raw.github.com/pypa/virtualenv/master/virtualenv.py')"
- python virtualenv.py venv **--no-setuptools**
- set-executionpolicy unrestricted
- python setup.py develop
- .\venv\Scripts\activate.ps1
- Download [ez_setup.py](https://bootstrap.pypa.io/ez_setup.py) and run it in the same PowerShell window - download the file into the sevabot folder and then just run python _ez_setup.py_
- Once finished, run _python setup.py develop_ again and then continue in the setup guide

Then it should work. Hope it fixes the issue for you.

Also just FYI: when running the sevabot on Windows, you are likely to run into this issue: https://github.com/opensourcehacker/sevabot/issues/58

**Comment by Lolmewn** [comment]
Awesome, it's actually running now! Getting errors on !ping, but I guess that's discussed in #58.

**Comment by YSunLIN** [comment]
I fixed when I change some code in "Lib/site-package/virtualenv.py".

    try:
        call_subprocess(cmd, show_stdout=False,
            extra_env = {
                'PYTHONPATH': pythonpath,
                'JYTHONPATH': pythonpath,  # for Jython < 3.x
                'PIP_FIND_LINKS': findlinks,
                'PIP_USE_WHEEL': '1',
                'PIP_PRE': '1',
                # 'PIP_NO_INDEX': '1'  # <-----here, comment here.
            }
        )
    finally:
        logger.indent -= 2
        logger.end_progress()

But I don't know why.
