### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by itsfolf** [opensourcehacker/sevabot#96]
I can't install sevabot, I have this error:

The term '\venv\Scripts\activate.ps1' is not recognized as the name of a cmdlet, function, script file, or operable pro
gram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:27
- \venv\Scripts\activate.ps1 <<<<
  - CategoryInfo          : ObjectNotFound: (\venv\Scripts\activate.ps1:String) [], CommandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

**Comment by miohtama** [comment]
As this seem to be an issue with virtualenv on Windows, I suggest you seek assistance on virtualenv mailing list https://groups.google.com/forum/#!forum/python-virtualenv or issue tracker https://github.com/pypa/virtualenv
